name: Deploy API to Remote Machines

on:
  push:
    path:
      - 'api/**' 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      
      - name: Add remote server to known_hosts
        run: mkdir -p ~/.ssh && echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Pull Latest Changes, Setup Virtual Environment, and Install Requirements on Other Servers
        run: |
          for n in 4 5 6; do
            ssh -o StrictHostKeyChecking=no -p 2200$n hal900$n@compute.hal9.com "cd comc_api/ && git stash && git pull origin main && \
            if [ ! -d '.venv' ]; then python3 -m venv .venv; fi && \
            chmod +x ./start.sh && ./start.sh $n"
          done
