name: Deploy API to Main Server

on:
  push:
    path:
      - 'main/**' 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      
      - name: Add remote server to known_hosts
        run: mkdir -p ~/.ssh && echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Pull Latest Changes, Setup Virtual Environment, and Install Requirements on Main Server
        run: |
          ssh -o StrictHostKeyChecking=no -p 22001 hal9001@compute.hal9.com "cd comc_api/ && git stash && git pull origin main && \
          if [ ! -d '.venv' ]; then python3 -m venv .venv; fi && \
          chmod +x ./start.sh && ./start.sh 1"
